//////////////////// ALL ASSIGNMENTS INCLUDE THIS SECTION /////////////////////
//
// Title: GeometricSequenceGenerator.java
// Files: ArithmeticSequenceGenerator.java, Sequence.java,
//////////////////// FibonacciSequenceGenerator.java, DigitProductSequenceGenerator.java,
//////////////////// SequenceGeneratorTests.java
// Course: CS300 Fall 2018
//
// Author: Reece Lardy
// Email: RLardy@wisc.edu
// Lecturer's Name: Alexander Brooks
//
///////////////////////////// CREDIT OUTSIDE HELP /////////////////////////////
//
// Students who get help from sources other than their partner must fully
// acknowledge and credit those sources of help here. Instructors and TAs do
// not need to be credited here, but tutors, friends, relatives, room mates,
// strangers, and others do. If you received no outside help from either type
// of source, then please explicitly indicate NONE.
//
// Persons: (identify each person and describe their help in detail)
// Online Sources: (identify each URL and describe their assistance in detail)
//
/////////////////////////////// 80 COLUMNS WIDE ///////////////////////////////
import java.util.Iterator; // import iterator

/**
 * This class represents a sequence generator for a geometric sequence
 * 
 * @author Reece Lardy
 * @implements Iterator
 */
public class GeometricSequenceGenerator implements Iterator<Integer> {
  private final int SIZE; // The number of elements in this sequence
  private final int INIT; // The first term in this sequence
  private final int RATIO; // The common ratio for this sequence
  private int next; // The next term in the sequence

  private int generatedCount; // The number of terms generated so far in this sequence
  // It refers also to the order of the next number to be generated by next() method

  // constructor
  public GeometricSequenceGenerator(int init, int ratio, int size) {
    // if there are invalid parameters
    if (init <= 0 || ratio <= 0) {
      // throw exception
      throw new IllegalArgumentException(
          "WARNING: The starting element and the common ratio for a geometric progression should be STRICTLY POSITIVE.");
    }
    // if there is an invalid size
    if (size <= 0) {
      // throw exception
      throw new IllegalArgumentException("WARNING: CANNOT create a sequence with size <= zero.");
    }
    // set variables to input parameters
    this.INIT = init;
    this.SIZE = size;
    this.RATIO = ratio;
    next = this.INIT;
    generatedCount = 0;

  }

  /**
   * Checks to see if there is another element to add to the sequence
   * 
   * @return boolean representing if the amount of generated elements in the sequence is less than
   *         size
   * @see hasNext() in iterator
   */
  @Override
  public boolean hasNext() {
    // time complexity: O(1)
    return generatedCount < SIZE;
  }

  /**
   * Returns the next element in the geometric sequence and changes next field to current and finds
   * the new next element
   * 
   * @return boolean representing if the amount of generated elements in the sequence is less than
   *         size
   * @see next() in iterator
   */
  @Override
  public Integer next() {
    // time complexity: O(1)
    if (!hasNext()) // check if the current element has a next element in this sequence
      return null;
    int current = next; // set the current element to next
    generatedCount++; // increment the number of generated elements so far
    next = next * RATIO; // set the next element (multiplies the ratio to the current number)
    return current; // return the current number as the generated one
  }
}
